[development]
  [development.mongo]
    host="mongodb://localhost/"
    database="blog"
  [development.redis]
    host="localhost"
    port=6379
    db=0
    decode_responses=true

[production]
  [production.mongo]
    host="mongodb://localhost/"
    database="blog"
  [production.redis]
    host="localhost"
    port=6379
    db=0
    decode_responses=true